/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";

export function Head(props) {
  const { nodes, materials } = useGLTF("models/scene.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, 0, 2.611]}
        rotation={[-1.92, 0, -Math.PI]}
        scale={2.762}
      >
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 43.978, 0]} rotation={[Math.PI / 4, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Phone_Case_PhoneCase_Mat_0.geometry}
              material={materials.PhoneCase_Mat}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Phone_Case_PhoneFace_Mat_0.geometry}
              material={materials.PhoneFace_Mat}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Camera_1_PhoneFace_Mat_0.geometry}
            material={materials.PhoneFace_Mat}
            position={[9.743, 58.839, -20.064]}
            rotation={[Math.PI / 4, 0, 0]}
            scale={1.696}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Camera_2_PhoneFace_Mat_0.geometry}
            material={materials.PhoneFace_Mat}
            position={[9.743, 55.578, -16.803]}
            rotation={[Math.PI / 4, 0, 0]}
            scale={1.696}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Camera_Front_PhoneButton_Mat_0.geometry}
            material={materials.PhoneButton_Mat}
            position={[-0.421, 66.193, -18.692]}
            rotation={[Math.PI / 4, 0, 0]}
            scale={0.575}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Camera_Light_Camera_Light1_0.geometry}
            material={materials.Camera_Light1}
            position={[6.831, 57.23, -18.455]}
            rotation={[Math.PI / 4, 0, 0]}
            scale={0.875}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Phone_Camera_PhoneCase_Mat_0.geometry}
            material={materials.PhoneCase_Mat}
            position={[8.421, 57.722, -17.875]}
            rotation={[Math.PI / 4, 0, 0]}
            scale={[0.889, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Power_Button_PhoneButton_Mat_0.geometry}
            material={materials.PhoneButton_Mat}
            position={[15.24, 54.694, -10.453]}
            rotation={[Math.PI / 4, 0, 0]}
            scale={[1, 1, 1.24]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Volume_Down_PhoneButton_Mat_0.geometry}
            material={materials.PhoneButton_Mat}
            position={[-15.121, 51.118, -7.296]}
            rotation={[0.787, 0, -3.053]}
            scale={[1, 1, 0.793]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Volume_Up_PhoneButton_Mat_0.geometry}
            material={materials.PhoneButton_Mat}
            position={[-15.122, 54.492, -10.657]}
            rotation={[0.787, 0, -3.053]}
            scale={[1, 1, 0.793]}
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Head.geometry}
        material={materials["Material.001"]}
        position={[0, 3.801, -1.862]}
        rotation={[0, 1.571, 0]}
      />
    </group>
  );
}

useGLTF.preload("models/scene.glb");
